mainLog = r'F:\PROJECTS\Team Project\Main\mainLog.json'
requestDir = 'F:\PROJECTS\Team Project\Main\Requests'
responseDir = 'F:\PROJECTS\Team Project\Main\Response'
reports = 'F:\PROJECTS\Team Project\Main\Reports'
cred = 'F:\PROJECTS\Team Project\Main\cred.bin'
