mainLog = r'F:\PROJECTS\Team Project\Main\mainLog.json'
compData = r'F:\PROJECTS\Team Project\Main\compData.json'
requestDir = 'F:\PROJECTS\Team Project\Main\Requests\\'
responseDir = 'F:\PROJECTS\Team Project\Main\Response'
reports = 'F:\PROJECTS\Team Project\Main\Reports\\'
cred = 'F:\PROJECTS\Team Project\Main\cred.bin'
attachments = 'F:\PROJECTS\Team Project\Main\MailAttachments'
